### ISSUE TITLE
Programmatically recenter map

### ISSUE THREAD

**Issue by nexttrack07** [googlemaps/react-native-navigation-sdk#202]
After using either `moveCamera` or `showRouteOverview`, is it possible to programmatically recenter the map instead of expecting the user to click on the recenter button? 

After either of those functions are called, the user is not centered and following the navigation path unless he clicks on `Re-center`

Thanks

**Comment by nexttrack07** [comment]
@illuminati1911 - Hey thanks for responding. However, I retested with the old version (0.3.3-beta) and the latest version (0.4.0) and it doesn't seem to work in either one. 

Here are the steps to reproduce in the latest example app: 
1. Set destination with some lat lng
2. Start simulation and guidance - This will cause the camera to follow the user simulation
3. Click `Show Route Overview` - This will cause camera to zoom out and show the entire view but simulation will continue
4. Select camera perspective using `setFollowingPerspective` (any of the three options) - This does **not** zoom in to the user and follow simulation

<img width="392" alt="Screenshot 2024-07-30 at 11 01 30 PM" src="https://github.com/user-attachments/assets/eaff439e-4faf-479a-a93d-3d7ba053d8c1">
<img width="394" alt="Screenshot 2024-07-30 at 11 02 16 PM" src="https://github.com/user-attachments/assets/c37cef50-d849-48b6-9018-f81c000a764c">

This is a critical bug for and we are eagerly awaiting your response. Our app release is very soon and we'd like to see if this is something we can fix.

**Comment by tfranzese-woolpert** [comment]
For iOS the camera mode needs to be set back to following:
```
setFollowingPerspective(CameraPerspective.TOP_DOWN_HEADING_UP);
setCameraMode(CameraMode.FOLLOWING);
```

I believe that API is specific to the iOS Navigation SDK, see https://developers.google.com/maps/documentation/navigation/ios-sdk/camera#automatically_recenter_the_map

**Comment by akilakumarasamy** [comment]
The map is not following the user's location during turn-by-turn navigation is a critical issue with the navigation functionality. This behavior is essential for the core functionality of the navigation project. Without this, the navigation experience is significantly compromised, making the application effectively unusable for its intended purpose.
This issue is a major blocker for our project's launch, and we are unable to proceed without a resolution. We would greatly appreciate for a fix or a viable workaround to address this problem.
