### ISSUE TITLE
Unable to do pod install on latest version of react native getting below error while trying to do pod install

### ISSUE THREAD

**Issue by jaykishan23** [googlemaps/react-native-navigation-sdk#336]
CocoaPods could not find compatible versions for pod "react-native-navigation-sdk"                                                                           In Podfile:
    react-native-navigation-sdk (from `../node_modules/@googlemaps/react-native-navigation-sdk`)

Specs satisfying the `react-native-navigation-sdk (from `../node_modules/@googlemaps/react-native-navigation-sdk`)` dependency were found, but they required a higher minimum deployment target.

**Comment by jokerttu** [comment]
Hi @jaykishan23 
Please update your platform version to 15.1 for RN 0.76
See: https://github.com/react-native-community/discussions-and-proposals/discussions/812

**Comment by jaykishan23** [comment]
Hello @jokerttu , I am using Xcode version 15.4 and react native version "0.75.4" still getting the same issue

**Comment by jokerttu** [comment]
Have you updated your platform version to iOS 15?

For reference, you can check this line in the example Podfile:
https://github.com/googlemaps/react-native-navigation-sdk/blob/main/example/ios/Podfile#L13

Just wanted to clarify since the Xcode version mentioned earlier is a different matter.

Also as mentioned above for 0.76 you should update it to 15.1:  https://github.com/googlemaps/react-native-navigation-sdk/issues/336#issuecomment-2478877666

**Comment by jokerttu** [comment]
@jaykishan23
Please check how example app is configured.
The above error is not related to navigation sdk package.
Make sure to clean `Podfile.lock` and reinstall pods with `pod install`.
Also check that you have done all necessary changes to your project with https://react-native-community.github.io/upgrade-helper/

Closing this issue as this is not related to this package.
