### ISSUE TITLE
Duplicate Classes Error in :app:checkDebugDuplicateClasses with react-native-navigation-sdk and react-native-maps

### ISSUE THREAD

**Issue by xmontalvvo** [googlemaps/react-native-navigation-sdk#363]
When implementing both @googlemaps/react-native-navigation-sdk (v0.8.1) and react-native-maps (v1.20.1) in a React Native project, a build error occurs during the :app:checkDebugDuplicateClasses task. The error arises from dependency conflicts between the libraries, particularly in the Google Play Services components (com.google.android.gms:play-services-*) and com.google.android.libraries.navigation:navigation.

The issue happens when running npm run android, as the conflicting dependencies prevent the project from compiling.

Both libraries are required for this project:

react-native-maps: Provides advanced map-related functionalities (e.g., detailed layers and advanced markers) that are not fully available in @googlemaps/react-native-navigation-sdk.
@googlemaps/react-native-navigation-sdk: Used specifically for its navigation features.

#### Error Log

```
> Task :app:checkDebugDuplicateClasses FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.android.gms.maps.CameraUpdate found in modules jetified-navigation-6.0.0-runtime (com.google.android.libraries.navigation:navigation:6.0.0) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)

```

I appreciate your prompt help in implementing the two libraries together in a major project, as there is a lot of code that has already been implemented with react-native-maps.

**Comment by jokerttu** [comment]
This issue is acknowledged in the [Known Issues](https://github.com/googlemaps/react-native-navigation-sdk#compatibility-with-other-libraries) section of the `@googlemaps/react-native-navigation-sdk` README.

To resolve this conflict, you can exclude the Google Maps SDK dependency from the Navigation SDK and enforce a consistent version across your project. This approach is effective only if the underlying APIs of the Google Maps SDK for Android are compatible with both `@googlemaps/react-native-navigation-sdk` and `react-native-maps`. Please note that while this solution may resolve the immediate build conflict, it is not officially recommended and may introduce other issues.
Look for gradle documentation for the gradle version you are using for futher information.
